### ISSUE TITLE
RIOT native port to ARM-9

### ISSUE THREAD

**Issue by marshall** [openkosmosorg/kubos-core#13]
After getting my code for #7 compiling on the BBB, it looks like the native port fails with a Bus error when trying to allocate the idle thread stack during a call to `getcontext()`, which is caused by the fact that the implementation of these functions for the RIOT `native` board use hand coded x86 assembler (and in general, the native port is listed as an x86 MCU, bringing the entire `boards/cpu/x86` directory with it):

https://github.com/RIOT-OS/RIOT/blob/master/boards/native/Makefile.features#L8

Unfortunately, all of the ARM CPU implementations are limited to ARM-7 / Cortex-M chips, meaning we'd need to start a new port for the BeagleBone ARM-9 / Cortex-A series.

This is probably a deal breaker for the STRAT-5 launch  unless someone is familiar enough with ARM assembler to get this running in the next week. @evanosky @punchcard60 thoughts?

**Comment by punchcard60** [comment]
Marshall,

Please call me at 214-450-7752. 
Thanks, 
Jon

On September 29, 2015 10:38:45 AM CDT, Marshall Culpepper <notifications@github.com> wrote:
>After getting my code for #7 compiling on the BBB, it looks like the
>native port fails with a Bus error when trying to allocate the idle
>thread stack during a call to `getcontext()`, which is caused by the
>fact that the implementation of these functions for the RIOT `native`
>board use hand coded x86 assembler (and in general, the native port is
>listed as an x86 MCU, bringing the entire `boards/cpu/x86` directory
>with it):
>
>https://github.com/RIOT-OS/RIOT/blob/master/boards/native/Makefile.features#L8
>
>Unfortunately, all of the ARM CPU implementations are limited to ARM-7
>/ Cortex-M chips, meaning we'd need to start a new port for the
>BeagleBone ARM-9 / Cortex-A series.
>
>This is probably a deal breaker for the STRAT-5 launch  unless someone
>is familiar enough with ARM assembler to get this running in the next
>week. @evanosky @punchcard60 thoughts?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openkosmosorg/kubos-core/issues/13

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by marshall** [comment]
Talked with @punchcard60 about this offline, and it seems like the ARM7 implementation might actually get used, and something is stepping on the stack in the thread control block. Jon added an extra 12 bytes to the block and was able to get his program to run..

**Comment by evanosky** [comment]
So have yall tried the fix? Are we closing this issue for strat-5 (or maybe moving it to backlog if hack?)

**Comment by marshall** [comment]
I haven't had a chance yet, but I know @punchcard60 has for his issue. 

Jon, can you jog my memory where in the code the 12 bytes were supposed to be added? Was it to the end of `tcb_t` in `core/include/tcb.h`?

**Comment by punchcard60** [comment]
Yes, that's correct. 

On September 29, 2015 7:47:34 PM CDT, Marshall Culpepper <notifications@github.com> wrote:
>I haven't had a chance yet, but I know @punchcard60 has for his issue. 
>
>Jon, can you jog my memory where in the code the 12 bytes were supposed
>to be added? Was it to the end of `tcb_t` in `core/include/tcb.h`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openkosmosorg/kubos-core/issues/13#issuecomment-144230252

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by punchcard60** [comment]
I dug into it a little deeper. The native RIOT board/cpu doesn't call any cpu specific code. All of the board/cpu specific stuff is handled by linux.

**Comment by marshall** [comment]
So we still need to figure out what's overflowing the stack, I've filed #14 as a follow up
