### ISSUE TITLE
RFC: Reorganize kubos-core structure

### ISSUE THREAD

**Issue by punchcard60** [openkosmosorg/kubos-core#28]
I believe that we need to reorganize the kubos github. I propose splitting kubos-core into kubos-core and kubos-apps repositories. Kubos-core would remain as an OS repository and kubos-apps would be a place to put the application level software. We might even consider individual repositories for each application, building towards a top level repository "kubos-flight-system" or something similar.
Within kubos-core I suggest that we parallel the RIOT structure or use something very similar.

**Comment by marshall** [comment]
+1 I like this suggestion, though we only have 1 actual 'application' right now -- the example at the top level. To do this properly we should use either git submodules or google's [repo](https://code.google.com/p/git-repo/) to manage the various github repositories. wdyt?

**Comment by marshall** [comment]
It might make sense to take this one step further and have 1 repository per application, that way we don't clutter one repository with all of our apps..

**Comment by punchcard60** [comment]
Question: if 1 app = 1 repository, how would the various app combinations be built into a single executable?

**Comment by marshall** [comment]
The RIOT expectation is that 1 app = 1 executable, I'm not sure how that relates to separate repositories?

**Comment by punchcard60** [comment]
I'm thinking in terms of combinations. How do we build an app that is beacon+detumbler or other combination if beacon is a repository and detumbler is a repository? Where do the makefiles live?

**Comment by marshall** [comment]
Good question -- I think it might make sense to use RIOT's module system for anything that can be combined in as a service/task into an application. To clarify, I'm only advocating separate repositories for separate apps, not modules/services/tasks.

Within the context of a RIOT module (many per app) or app (1 per MCU), there is a well defined Makefile infrastructure that integrates with the existing RIOT build system

**Comment by punchcard60** [comment]
Either that or a repository that has a makefile that let's us specify what apps to build. I'm thinking that beacon is an app, but APRS and AX.25 are modules (netapi2 modules to be specific).

On December 12, 2015 9:06:26 AM CST, Marshall Culpepper <notifications@github.com> wrote:
>Good question -- I think it might make sense to use RIOT's module
>system for anything that can be combined in as a service/task into an
>application. To clarify, I'm only advocating separate repositories for
>separate apps, not modules/services/tasks.
>
>Within the context of a RIOT module (many per app) or app (1 per MCU),
>there is a well defined Makefile infrastructure that integrates with
>the existing RIOT build system 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openkosmosorg/kubos-core/issues/28#issuecomment-164160142

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NickTompkins123** [comment]
Apps can be examples correct?
