### ISSUE TITLE
Getting Started Build Setup

### ISSUE THREAD

**Issue by punchcard60** [openkosmosorg/kubos-core#29]
Kubos needs an automated way for new developers to fork/clone all of the appropriate repositories (including RIOT) and begin developing.

**Comment by marshall** [comment]
Some good examples of how this can be done:

* In [FirefoxOS (Boot2Gecko)](https://github.com/mozilla-b2g/B2G/tree/master/config.sh) this is done with a simple configuration script in a top level repository that uses [repo](https://code.google.com/p/git-repo/) to pull down all the appropriate repositories and branches
* With `git submodule update --init` you can checkout all git submodules of a master repository with one command

**Comment by marshall** [comment]
The beginnings of this now live in our [KubOS README](http://github.com/openkosmosorg/KubOS/tree/master/README.md)
