### ISSUE TITLE
Port Vanguard GPS Python Code to KubOS

### ISSUE THREAD

**Issue by evanosky** [openkosmosorg/kubos-core#3]
- [x] Learn about Vanguard implementation of GPS
- [x] Put manual instructrustion run and initialize gpsd on native port
- [x] Access GPS location using libgps C library (follow python equivalent called in vanguard)
- [x] Port vanguard functionality to module
- [ ] Use riot-based uart periph vs linux specific implementation

**Comment by evanosky** [comment]
Looks like Vanguard used gpsd -- a Daemon for Linux which can do a lot of the heavy lifting for the 'native' kubos port.  http://catb.org/gpsd/.  Need to initialize in similar way and use libgps vs python client to access daemon service.  Turning these into tasks...

**Comment by evanosky** [comment]
Status Update: Added shell command "gps_get" and was able to get results! gpsd w/ virtual GPS running via fakegps python utility and gps.log found in vanguard test folder.  Code not checked in yet...will refactor and check in soon.

**Comment by evanosky** [comment]
Checked in first hack at location module.  Put manual instructions on how to run fakegps if real gps not connected.  Removing task from this issue to automate -- will add new task to build automated testing for all features.

**Comment by marshall** [comment]
We are using raw NMEA and UART now instead of gpsd, closing
