### ISSUE TITLE
Integrate Kubos TNC

### ISSUE THREAD

**Issue by evanosky** [openkosmosorg/kubos-core#4]
Re-purposing this issue for new radio cape integration.  Added separate vanguard port issue to Strat-5 milestone

**Comment by jessehamner** [comment]
## Controlling the modem

Controlling the modem will involve some control logic, pin asserts, and pin sensing. For instance, to turn the modem off, or to set the mode in which it will operate ( TX, or RX ):

M1 | M0 | Rx Mode | Tx Mode | Data Retime
--- | --- | --- | --- | ---
0  | 0 | 1200bps | 150bps | Rx
0 | 1 | Off | 1200bps | Tx
1 | 0 | 1200bps | Off / 5bps | Rx
1 | 1 | 'Zero-Power' | - | -

## Furthermore:
* The OS will need to poll the DET pin to see if the modem is hearing anything from the RX radio. 
* To avoid "all ears, no mouth" problems, there should be program logic that prevents the "energy detect" (DET) pin from preventing telemetry/location packets from being sent. Let's pick 15 seconds for testing. After 15 seconds, RX will be interrupted until telemetry packets are sent. 
* The OS will need to poll the RSSI pin from the RX2A for signal strength indicators. This will give us useful information on the ground, delivered via APRS "message" packets (compared with "location" packets) on the general set of sensors and system health. 
* Temperature data should be sent in the "message" packets, e.g., but that spec belongs elsewhere.

**Comment by jessehamner** [comment]
## Sending data

M1 | M0 | TXD = 0 | TXD = 1
--- | --- | --- | ---
1 | 1 | - | -
1 | 0 | 0Hz | 387Hz
0 | 0 | 487Hz | 387Hz
**0** | **1** | **2200Hz** | **1200Hz**

**Comment by punchcard60** [comment]
Jesse, thanks for the info. I'm just now starting to work on this.

**Comment by punchcard60** [comment]
What specific model/rev Beaglebone is being used for Strat-5?

**Comment by jessehamner** [comment]
Beaglebone Black -- and I desperately hope the revision type (they're up to "C" now, I think?) doesn't matter. We _have_ had some problems with several BBBs misbehaving that _could_ be related to changes made in earlier vs. later revisions. So get & build against the latest BBB if possible.

**Comment by punchcard60** [comment]
I thought I left this comment several hours ago, but apparently I didn't. argh!

@Jesse thanks.

This is what I think the radio thing looks like:

![block diagram](https://cloud.githubusercontent.com/assets/6411879/10087651/c15f5588-62da-11e5-8a93-cd003fdaefc7.png)

If anybody wants to add or correct anything, I'm all ears! Otherwise I'll move forward with trying to build it.

**Comment by evanosky** [comment]
Moving this issue to Strat-6 milestone -- Strat-5 will stick to audio port & direwolf

**Comment by marshall** [comment]
@punchcard60 your diagram looks right, and in fact most of the APRS, AX.25, and KISS framing parts have been taken care of in the new `ham` module that I merged a few weeks ago.

Would you mind taking a look over the code?

**Comment by punchcard60** [comment]
Sure.

**Comment by punchcard60** [comment]
What was formerly the Radio Cape for Beaglebone Black has been renamed and generalized to Kubos TNC module. This module should be adaptable to all mpu cards.
