### ISSUE TITLE
Write Test Suite for Strat-5 Features

### ISSUE THREAD

**Issue by evanosky** [openkosmosorg/kubos-core#6]
Should do tests as each new feature implemented...however for this time around, focused on discovery for each of the features.  Will use this issue to make sure we return to the tests before launch Strat-5.
- [x] location/gps module tests
- [ ] radio module tests
- [ ] beacon module tests

**Comment by evanosky** [comment]
For GPIO testing, should be consider QEMU and Beaglebone emulation?  Don't know how else to test GPIO...

**Comment by marshall** [comment]
Check the test suite in the python code -- most of the GPIO assertions are just mocking out the filesystem API (GPIOs in Linux simply use the sysfs)

**Comment by evanosky** [comment]
merged latest pull request from punchcard60-test-suite -- good enough for gps/location

**Comment by marshall** [comment]
I'd rather we make sure that unit tests are added for each new module before they are merged..
