### ISSUE TITLE
Implement periph/uart for native within RIOT-OS branch

### ISSUE THREAD

**Issue by evanosky** [openkosmosorg/kubos-core#7]
RIOT-OS has a peripheral interface already defined for RIOT-OS, however the native port doesn't have it implemented

For STRAT-5, we can open up linux serial port directly, but it won't be a cross-board implementation.  To implement, we'll need to fork riot-os and implement.  Confirmed with devel@riot-os.org mailing list that this is a gap, however no issue created in their database (that i could find).

- [x] Write code
- [x] Test with hardware
- [x] Put RiotOS fork into openkosmosorg
- [x] Make sure built-in RIOT tests for uart passes

**Comment by evanosky** [comment]
Marshall says code is written -- needs to test w/ hw now

**Comment by marshall** [comment]
RIOT supports third party hardware using `RIOTCPU` and `RIOTBOARD` Make variables, so I will try to get this all moved over to kubos-core to keep things separate.
